[project]
name = "vsc-sync"  # 或者 vsc-refresh
version = "0.1.0"
description = "Automated VSCode configuration management and rebuild tool"
readme = "README.md"
authors = [
    { name = "Dannis", email = "hzzhanyuyang@gmail.com" }
]
requires-python = ">=3.10"

[project.scripts]
vsc-sync = "sync.vsc.vscode_config:main"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.uv]
package = true
